#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
#export PATH="$HOME/.local/share/neovim/bin":$PATH
#export PATH="$PATH:./node_modules/.bin"
# eval "$(zoxide init zsh)"

# C Programming
export CC='clang'

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Locale/Langs
export LANG='en_US.utf8'
export LC_ALL='en_US.utf8'

# Programs
export EDITOR="nvim"
export VISUAL="nvim"
export FILE_BROWSER="vifm"
export VID_PLAYER="vlc"

export ZSH_COMPDUMP=~/.cache/.zcompdump-$HOST


# make bat show man page
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# export PYTHONPATH=/home/dd/.local/lib/python3.10/site-packages:/usr/lib/python3/dist-packages

export PATH=$PATH:/usr/local/go/bin
