#!/usr/bin/zsh

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lh="ls -hl"


alias c="clear"
alias nvimrc='nvim ~/.config/nvim/'
alias vrc='cd ~/.config/nvim'

alias vim=nvim
alias vimdiff='nvim -d'
alias vifm=vifmrun
alias fd=fdfind
alias du=dust
alias nf="neofetch"
# alias python=python2
alias cat="bat --plain"
alias lg='lazygit'
alias pick='thumbs -u -r | xsel --clipboard -i'

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# alias ls="exa"
# confirm before overwriting something
alias mv="mv -vi"
alias cp="cp -vri"
alias rm="rm -vri"

alias df=duf
alias free='free -m' # show sizes in MB

alias setclip="xclip -selection c"
alias getclip="xclip -selection c -o"

# mkdir
alias mk="mkdir -p"
alias mkdir="mkdir -p"

# Use less fuck
alias sl=ls

# CD
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias ~="cd ~"


# Suffix aliases
alias -s txt=nvim

# open ~/.zshrc in using the default editor specified in $EDITOR
alias ec="$EDITOR $HOME/.zshrc"

# source ~/.zshrc
alias sc="source $HOME/.zshrc"

alias background_local='printf "\e]11;#282828\e\\"'
alias background_server='printf "\e]11;#2E3440\e\\"'
alias ssh_nuc="background_server; ssh nvio_t ; background_local"
alias planner='flatpak run com.github.alainm23.planner'
