#!/bin/sh
# Function to source files if they exist
function zsh_add_file() {
    [ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1"
}

function zsh_add_plugin() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ]; then 
        # For plugins
        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
    else
        git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME"
    fi
}

function zsh_add_completion() {
    local repo="$1"
    local initialize="${2:-false}"
    local plugin_name="${repo##*/}"
    local plugin_dir="$ZDOTDIR/plugins/$plugin_name"
    local completion_file
    local completion_dirs=()

    if [ -d "$plugin_dir/.git" ]; then
        git -C "$plugin_dir" pull --ff-only >/dev/null 2>&1 || true
    elif [ -d "$plugin_dir" ]; then
        :
    else
        git clone "https://github.com/$repo.git" "$plugin_dir"
    fi

    for completion_file in "$plugin_dir"/_*; do
        [ -e "$completion_file" ] || continue
        local completion_dir
        completion_dir=$(dirname "$completion_file")
        case " ${fpath[*]} " in
            *" $completion_dir "*) ;;
            *) completion_dirs+=("$completion_dir") ;;
        esac
    done

    if [ "${#completion_dirs[@]}" -gt 0 ]; then
        fpath=("${completion_dirs[@]}" "${fpath[@]}")
    fi

    zsh_add_file "plugins/$plugin_name/$plugin_name.plugin.zsh"

    rm -f "$ZDOTDIR/.zccompdump"

    if [ "$initialize" = true ]; then
        compinit -i
    fi
}

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

mktouch() { mkdir -p "$(dirname "$1")" && touch "$1"; }
