#! /usr/bin/bash

# clear the log file
: > $HOME/.config/bspwm/start.log 

$HOME/.config/bspwm/screen_setup.sh $1 >> $HOME/.config/bspwm/start.log &
$HOME/.config/bspwm/autolaunch.sh $1 >> $HOME/.config/bspwm/start.log &
# bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
# bspc monitor HDMI-2 -d 1 2 3 4 5 6 7 8 9



bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
bspc config top_padding 0


bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a rviz desktop='^4' follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a SimpleScreenRecorder state=floating follow=on
bspc rule -a PlotJuggler-3 desktop='^5' follow=on
# bspc rule -a Chat-gpt desktop='^7' state=floating follow=on center=true rectangle=1200x800+0+0 
bspc rule -a Gnome-calculator desktop='^8' state=floating follow=on
bspc rule -a Mendeley\ Desktop desktop='^9' follow=on 
# bspc rule -a Google-chrome desktop='^1'
bspc rule -a netease-cloud-music desktop='^6' state=floating follow=on center=true rectangle=1200x800+0+0 
bspc rule -a pomotroid desktop='^3' follow=off locked=on -o state=floating rectangle=350x470+1500+100
bspc rule -a wechat desktop='^7' follow=on locked=on -o state=floating  rectangle=1800x1300+960+600


#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



# Remove x cursor
# xsetroot -cursor_name left_ptr &

#enable touchpad tapping and natural scrolling
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1

