#! /bin/sh

$HOME/.config/bspwm/autolaunch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

# rule -a  google-chrome                    follow=on focus=on


bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
bspc config top_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Gnome-calculator sktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^1'
bspc rule -a netease-cloud-music desktop='^6' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



# Remove x cursor
# xsetroot -cursor_name left_ptr &

#enable touchpad tapping and natural scrolling
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
