#! /bin/sh


# Run keybindings daemon.sxhkdrcgen
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/bspwm.sxhkdrc \
$HOME/.config/sxhkd/system.sxhkdrc $HOME/.config/sxhkd/user.sxhkdrc  &

# Start picom daemon
picom --config $HOME/.config/picom/picom.sample.conf -b

# Start ibus daemon
ibus-daemon -drx  &

# run polybar
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9

rule -a  google-chrome                    follow=on focus=on


bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
bspc config top_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Gnome-calculator sktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


# Start X wallpaper.
feh --no-fehbg --bg-fill $HOME/dotfiles/bin/wallpapers/japan01.png&

# Remove x cursor
xsetroot -cursor_name left_ptr &

#enable touchpad tapping and natural scrolling
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
# xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
